# .github/workflows/docker-build.yml

name: Build, Test, and Deploy Results

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Add permissions for the job to write to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Run 'mvn test'
      - name: Run tests and generate reports
        run: mvn test

      # 4. --- FIX IS IN THIS STEP ---
      #    This creates the index.html file inside the reports folder
      - name: Generate Test Report index.html
        run: |
          echo "<html><head><title>Test Reports</title></head><body>" > target/surefire-reports/index.html
          echo "<h1>Test Reports</h1><ul>" >> target/surefire-reports/index.html
          for file in target/surefire-reports/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # --- THIS IS THE LINE I FIXED ---
              echo "<li><a href=\"$filename\">$filename</a></li>" >> target/surefire-reports/index.html
            fi
          done
          echo "</ul></body></html>" >> target/surefire-reports/index.html

      # 5. Upload the test reports folder (which now includes index.html)
      - name: Upload test reports
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/surefire-reports'

      # 6. Also build the Docker image to prove it works
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: message-router:latest

      # 7. Deploy the uploaded reports to GitHub Pages
      - name: Deploy test results to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4