# .github/workflows/docker-build.yml

name: Build Docker Image and Run Tests

on:
  # Run this on 'push' to the main branch
  push:
    branches: [ main, master ]
  # Also allow running it manually from the "Actions" tab
  workflow_dispatch:

jobs:
  build-and-test:
    # Run this on the latest Ubuntu server
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code (including the Dockerfile)
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Docker's build-in-cache system
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. This is the command that does all the work
      - name: Build and test Docker image
        uses: docker/build-push-action@v5
        with:
          # Tell it where your Dockerfile is
          context: .
          file: ./Dockerfile

          # This is the key: push: false
          # This tells the action to ONLY build the image
          # and NOT push it to a registry.
          # The build itself will run the 'mvn package' and tests.
          push: false

          # Give the image a tag
          tags: message-router:latest